---
slug: Idris-book
filename: Idris-book
title: Idris for Everybody
description: Change me.
author: Jason Felice
copyright: 2017
uuid: e90e22fa-9b80-49c4-81cf-b7f459e48ea7
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
